# -*- coding: utf-8 -*-
"""Lab 4: Tuple Dict Set

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rZxGkiQwvIhDAoiRYierRoJRIOhxiW3b

# 1.Tuple and List
"""

file=open('score.csv')
all_scores=[]
for line in file:
  tokens = line.split(',')
  tokens = [int(e) for e in tokens]
  all_scores.append(tuple(tokens))
file.close()
new_scores = sorted(all_scores)
for i in new_scores:
  print(i[0],i[1],i[2],i[3],i[4],i[5],sum(i[1:]))

file=open('score.csv')
all_scores=[]
for line in file:
  tokens = line.split(',')
  tokens = [int(e) for e in tokens]
  total = 0
  for i in range(1,len(tokens)):
    total += tokens[i]
  tokens.append(total)
  all_scores.append(tokens)
all_scores = sorted(all_scores, key = lambda all_scores :(all_scores[-1],all_scores[0]),reverse = True)
for e in all_scores:
  print(e[0],e[1],e[2],e[3],e[4],e[5],e[6])
file.close()

"""# 2.Counting Using Dictionary"""

file = open('CH3Thailand Posts.csv','r')
hashtag = []
for line in file:
  counter = dict()
  data = line.strip().split()
  for e in data:
    if e[0] == '#':
      hashtag.append(e)
  for e in hashtag:
    if e in counter:
      counter[e] += 1
    else:
      counter[e] = 1
print(counter)

"""# 3.API and json"""

import requests
max_temp = 0
time = ''
ret = requests.get('http://api.openweathermap.org/data/2.5/forecast?zip=10330,th&APPID=7743f38ce634083abe786e2d679955e3&units=metric')
d = dict(ret.json())
for data in d['list']:
  if data['main']['temp'] > max_temp:
    max_temp = data['main']['temp_max']
    time = data['dt_txt']
print(time, max_temp)