# -*- coding: utf-8 -*-
"""Adv Com Prog-Lab 2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ufXgHcyt5ZLpxyO3ejC4Yz1Af_-xn_9D

# 1.Expression
"""

import math

degree = float(input('Enter degree: '))
radian1 = degree * math.pi/180
radian2 = math.radians(degree)
print('From equation: ' ,radian1)
print('From math.radians: ' ,radian2)

"""# 2.String"""

punctuations = '''!()-[]{};:'"\, <>./?@#$%^&*_~'''

input_str = input("Input sentence: ")
output_str = ""
for char in input_str:
  if char not in punctuations:
    output_str = output_str +char

print("Remove punctuations: " + output_str.replace(" ",""))
print("Total characters: ",len(output_str.replace(" ","")))

"""# 3.File"""

max = 0

file = open('score.csv')
file.readline()
for line in file:
  data = line.strip().split(',')
  sum = 0
  for i in range(1,6):
    sum = sum + int(data[i])
  if (sum > max):
    max = sum
print("Highest total score is",max)

"""# 4.PM2.5"""

max = 0
num = 0
row = 0
file = open('pm25.csv')
for line in file:
  data = line.strip().split(',')

  for i in range(1,2):
    if (data[i] != '-'):      
      num = int(data[i])
  if (num > max):
    max = num
    time = data[0]
      

print("The highest pm2.5 is",max)
print("The highest date/time is",time)