# -*- coding: utf-8 -*-
"""Lab 7: MongoDB.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DqnrOtICO3Q8x_8U4-0Qwdjmig5jmb70

# 1. pymongo **insert**
"""

pip install pymongo[srv]

client = pymongo.MongoClient("mongodb+srv://usertest:mike12345@cluster0.ob578.mongodb.net/test?retryWrites=true&w=majority")
db = client.student_scores

import pymongo

file=open('score.csv')
all_scores=[]
for line in file:
  sum= int(quiz1)+int(quiz2)+int(quiz3)+int(quiz4)+int(quiz5)
  id,quiz1,quiz2,quiz3,quiz4,quiz5=line.split(',')
  all_scores.append({'id':id,'quiz1':int(quiz1),'quiz2':int(quiz2),'quiz3':int(quiz3),'quiz4':int(quiz4),'quiz5':int(quiz5),'sum':int(sum)})
file.close()
for e in all_scores:
  db.scores.insert_one(e)

import pymongo

file=open('score.csv')
all_scores=[]
for line in file:
  sum= int(quiz1)+int(quiz2)+int(quiz3)+int(quiz4)+int(quiz5)
  id,quiz1,quiz2,quiz3,quiz4,quiz5=line.split(',')
  all_scores.append({'id':id,'quiz1':int(quiz1),'quiz2':int(quiz2),'quiz3':int(quiz3),'quiz4':int(quiz4),'quiz5':int(quiz5),'sum':int(sum)})
file.close()
db.scores.insert_many(all_scores, ordered=False)

"""# 2. pymongo find_one"""

import pymongo

data=db['scores']
doc=data.find()
student_id = input("Please enter an id: ")
for x in doc:
  if (x['id'] == student_id):
    print('Sum score: ',x['sum'])

"""# 3. pymongo find (condition and sort)"""

import pymongo

docs=db.scores.find({'sum':{'$gt':26}}).sort('sum', pymongo.DESCENDING)
for e in docs:
  print(e['id'],e['quiz1'],e['quiz2'],e['quiz3'],e['quiz4'],e['quiz5'],e['sum'])

"""# 4. pymongo find"""

import pymongo

air_bnb_db = client.sample_airbnb
documents=air_bnb_db['listingsAndReviews']
docs = documents.find({'address.country':'Brazil'})
for line in docs:
  print(line['name'],', ',line['address']['country'])