# -*- coding: utf-8 -*-
"""Lab 5:Pandas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17FEjJmXccFmDpbHf8pHEQC-hBocZLd4Y

# 1.Histogram of Sum of Student Score
"""

import pandas as pd

df=pd.read_csv('score.csv')
df.columns= ['id', 'quiz1', 'quiz2', 'quiz3', 'quiz4', 'quiz5']
column_score= list(df)
column_score.remove('id')
df['total']= df[column_score].sum(axis=1)
df['total'].hist(bins=12)

"""# 2.Titanic"""

import pandas as pd

df=pd.read_csv('train.csv')
filtered_df= df[['Survived', 'Sex', 'PassengerId']]
order= ['male','female']
df2 = pd.pivot_table(filtered_df, index='Survived', columns='Sex', aggfunc='count')['PassengerId']
df2= df2[order]
df2.plot(kind='bar')

"""# 3.Other Idea

Which region produced the largest profit?
"""

import pandas as pd

df=pd.read_csv('sales.csv')
filtered_df= df.groupby(['Region']).sum().reset_index()
filtered_df.plot.bar(x='Region', y='Total Profit')
