# -*- coding: utf-8 -*-
"""Lab 6:Seaborn and Plotly.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hX_8oify-XbjHu_up5s_1dMkWIpCJdod

# 1.Pairplot
"""

import pandas as pd
import seaborn as sbs

df=pd.read_csv('Iris.csv')
temp_df=df.T.iloc[1:]
temp_df=temp_df.T
sbs.pairplot(temp_df, hue='Species')

"""The attributes that is easiest to classify the thrree classes is the width of the petal, because most of the data from each class does not overlap each other.

# 2.Colored PM2.5
"""

import pandas as pd
import seaborn as sb

pm_df=pd.read_csv('pm25.csv')
pm_df.columns=['dt','pm']
pm_df=pm_df[pm_df['pm'] != '-']
pm_df['pm']=pd.to_numeric(pm_df['pm'])
pm_df['dt']=pd.to_datetime(pm_df['dt'])
pm_df['hr']=pm_df['dt'].dt.hour

def get_color(x):
  if x >= 36:
    return 'yellow'
  else:
    return 'green'

mean_by_hr=pm_df.groupby('hr').mean()
color_bar = [get_color(x) for x in mean_by_hr['pm']]
sb.barplot(data=pm_df,x='hr',y='pm', palette= color_bar)

"""# 3.What are the top 25 video game publisher total sales in millions?"""

import pandas as pd
import seaborn as sb
import matplotlib.pyplot as plt

df=pd.read_csv('vgsales.csv')
temp_df=df.groupby('Publisher').sum()
temp_df.reset_index(inplace=True)
fig,ax=plt.subplots(figsize=(24,8))
chart=sb.barplot(x='Publisher', y='Global_Sales', data=temp_df.sort_values('Global_Sales',ascending=False)[:25])
chart.set_xticklabels(chart.get_xticklabels(), rotation=90)
